### ISSUE TITLE
请问邮箱设置里面，怎么填授权码？

### ISSUE THREAD

**Issue by kesonn** [CTF-MissFeng/Watchdog#1]
请问邮箱设置里面，怎么填授权码？

**Comment by CTF-MissFeng** [comment]
授权码就是密码

**Comment by kesonn** [comment]
测试的邮件发送成功了，但是某个主域名下的任务都扫描完了，我的邮箱没有收到域名更新或者任务结果的邮件。

**Comment by CTF-MissFeng** [comment]
邮件是用来发送xray漏扫结果的，有漏洞会定时发送漏洞信息，且邮件发送代码被注释了，你可以手动去掉注释
