### ISSUE TITLE
flask出问题

### ISSUE THREAD

**Issue by alpha302** [CTF-MissFeng/Watchdog#2]
使用flask createdb有问题。

![NI1062YSZ{~GPHV8MKQ6A51](https://user-images.githubusercontent.com/55012418/82285097-2e28e980-99cd-11ea-8cb7-34477d4e51f9.png)

**Comment by CTF-MissFeng** [comment]
> 使用flask createdb有问题。
> 
> 
> 
> ![NI1062YSZ{~GPHV8MKQ6A51](https://user-images.githubusercontent.com/55012418/82285097-2e28e980-99cd-11ea-8cb7-34477d4e51f9.png)
> 
> 

请用python3.8运行

**Comment by alpha302** [comment]
好了，确实是pyenv没开。感谢

**Comment by dunhongqiao** [comment]
> 
> 
> 好了，确实是pyenv没开。感谢

为啥我这也是报错 开启env也不行

**Comment by CTF-MissFeng** [comment]
> > 好了，确实是pyenv没开。感谢
> 
> 为啥我这也是报错 开启env也不行

给截图
